name: OWASP Dependency-Check for Flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'base_project'
          path: '.'
          format: 'JSON'
          out: './dependency-check-report.json'

      - name: Verify Report File
        run: |
          if [ -f ./dependency-check-report.sarif ]; then
          echo "Report file exists."
          else
          echo "Report file not found!"
          exit 1
          fi

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.json
