name: Snyk Flutter Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Snyk to check for vulnerabilities
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
        id: snyk
        with:
          snyk-version: v1.391.0
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Snyk version
        run: echo "${{ steps.snyk.outputs.version }}"
      - name: Snyk monitor 
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
